### PR TITLE
Fix the first day of the month calculation

### PR DESCRIPTION
**Pull request by kuzaxak**
`datetime.datetime.now().replace(month=selected_month)` gives fatal if you request a report for March as if you have more days than February as an example

### CODE REVIEW

**Comment by kuzaxak** [comment]
!deploy

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-12/3/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-12/3//console)).

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-12/3/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-12/3//console)).

**Comment by qdo-deployer** [comment]
Deploy failed or was aborted. @kuzaxak, please check the logs [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-12/3/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-12/3//console)).

**Comment by kuzaxak** [comment]
!deploy

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-12/5/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-12/5//console)).

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-12/5/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-12/5//console)).

**Pull request merged**
