### PR TITLE
Web server

### PR DESCRIPTION
**Pull request by kuzaxak**

### CODE REVIEW

**Comment by kuzaxak** [comment]
!deploy

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/2/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/2//console)).

**Comment by kuzaxak** [comment]
!deploy

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/4/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/4//console)).

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/4/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/4//console)).

**Comment by qdo-deployer** [comment]
Deploy failed or was aborted. @kuzaxak, please check the logs [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/4/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/4//console)).

**Comment by kuzaxak** [comment]
!deploy

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/8/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/8//console)).

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/8/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/8//console)).

**Comment by qdo-deployer** [comment]
Deploy failed or was aborted. @kuzaxak, please check the logs [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/8/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/8//console)).

**Comment by kuzaxak** [comment]
!deploy

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/10/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/10//console)).

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/10/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-3/10//console)).

**Pull request merged**
