### PR TITLE
Add billable time calculator for Insly project

### PR DESCRIPTION
**Pull request by kuzaxak**
Tracking time got converted into invoiced hours and set to the tasks automatically.

Support for additional projects will be done later on

### CODE REVIEW

**Comment by kuzaxak** [comment]
!deploy

**Comment by qdo-deployer** [comment]
## Infrastructure changes detected


### beta

<details><summary>Output</summary>

```diff

default, clickup-report, Deployment (apps) has changed:
  # Source: clickup-report/templates/deployment.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: clickup-report
    labels:
      helm.sh/chart: clickup-report-0.1.0
      app.kubernetes.io/name: clickup-report
      app.kubernetes.io/instance: clickup-report
      app.kubernetes.io/version: "1.16.0"
      app.kubernetes.io/managed-by: Helm
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: clickup-report
        app.kubernetes.io/instance: clickup-report
    template:
      metadata:
        labels:
-         version: "3660b9e"
+         version: "5fe1af2"
          app.kubernetes.io/name: clickup-report
          app.kubernetes.io/instance: clickup-report
      spec:
        serviceAccountName: clickup-report
        securityContext:
          {}
        containers:
          - name: clickup-report
            securityContext:
              {}
-           image: "096568705843.dkr.ecr.eu-west-1.amazonaws.com/clickup-report:3660b9e"
+           image: "096568705843.dkr.ecr.eu-west-1.amazonaws.com/clickup-report:5fe1af2"
            imagePullPolicy: IfNotPresent
            env:
              - name: CLICKUP_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    key: clientID
                    name: clickup-report-secret
              - name: CLICKUP_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    key: clientSecret
                    name: clickup-report-secret
              - name: CLICKUP_SERVER_NAME
                value: clickup-reports.beta.hdo.ee
              - name: CLICKUP_URL_SCHEME
                value: "https"
              - name: CLICKUP_SESSION_SECRET
                valueFrom:
                  secretKeyRef:
                    key: session
                    name: clickup-report-secret
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP
            readinessProbe:
              httpGet:
                path: /healthz
                port: http
                httpHeaders:
                  - name: Host
                    value: clickup-reports.beta.hdo.ee
            resources:
              requests:
                cpu: 30m
                memory: 64Mi
        nodeSelector:
          kubernetes.io/arch: arm64
        tolerations:
          - effect: NoSchedule
            key: arch
            operator: Equal
            value: arm

```
</details>

---
**Warning**: This is preview of the plan, actual plan may change during the     **deploy** stage if the `master` branch was changed in between.

* :arrows_counterclockwise: To plan again, push a new commit or comment:
  * `!plan`



*Last updated at 2023/09/07 19:54:42*

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-7/2/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-7/2//console)).

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-7/2/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-7/2//console)).

**Comment by qdo-deployer** [comment]
Deploy failed or was aborted. @kuzaxak, please check the logs [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-7/2/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-7/2//console)).

**Comment by kuzaxak** [comment]
!deploy

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-7/4/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-7/4//console)).

**Comment by qdo-deployer** [comment]
@kuzaxak, your input is required [here](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-7/4/display/redirect) (or [in the old UI](https://ci.beta.hdo.ee/job/Github%20CI/job/clickup-billing-report/job/PR-7/4//console)).

**Pull request merged**
